
'use server';
/**
 * @fileOverview Provides a general chat flow using the configured Genkit AI instance.
 *
 * - chat - A function to send a message to the LLM and get a response.
 * - ChatInput - The input type for the chat function.
 * - ChatOutput - The return type for the chat function.
 */

import { ai } from '@/ai/ai-instance';
import { z } from 'genkit';
import type { MessageData } from 'genkit'; // Import MessageData type

// Input Schema: User message, optional context history, optional system prompt
const ChatInputSchema = z.object({
  message: z.string().describe('The user message to send to the LLM.'),
  context: z.array(z.any()).optional().describe('Optional conversation history or context messages. Each item should conform to Genkit MessageData structure.'),
  systemPrompt: z.string().optional().describe('Optional system prompt to guide the LLM.'),
});
export type ChatInput = z.infer<typeof ChatInputSchema>;

// Output Schema: The LLM's response
const ChatOutputSchema = z.object({
  response: z.string().describe('The response generated by the LLM.'),
});
export type ChatOutput = z.infer<typeof ChatOutputSchema>;

/**
 * Sends a message to the configured LLM, optionally including context and a system prompt.
 * @param input - The chat input containing the message and optional context/system prompt.
 * @returns A promise that resolves to the LLM's response.
 */
export async function chat(input: ChatInput): Promise<ChatOutput> {
  return chatFlow(input);
}

// Define the Genkit flow
const chatFlow = ai.defineFlow<typeof ChatInputSchema, typeof ChatOutputSchema>(
  {
    name: 'chatFlow',
    inputSchema: ChatInputSchema,
    outputSchema: ChatOutputSchema,
  },
  async (input) => {
    // Construct messages array for the LLM
    const messages: MessageData[] = [];

    // Add optional system prompt first if provided
    if (input.systemPrompt) {
        messages.push({ role: 'system', content: [{ text: input.systemPrompt }] });
    }

    // Add optional context messages
    // Basic validation: check if context looks like MessageData[]
    if (input.context && Array.isArray(input.context)) {
         input.context.forEach((msg: any) => {
            // Attempt to add context messages, assuming they fit MessageData structure
            if (msg && typeof msg.role === 'string' && Array.isArray(msg.content)) {
                messages.push(msg as MessageData);
            } else {
                console.warn("Skipping invalid context message:", msg);
            }
        });
    }

    // Add the current user message last
    messages.push({ role: 'user', content: [{ text: input.message }] });

    // Generate the response using the configured model
    const llmResponse = await ai.generate({
      prompt: messages, // Use the constructed messages array
      model: ai.getModel(), // Use the default model configured in ai-instance.ts
      config: {
        // Add any specific generation config if needed, e.g., temperature
      },
    });

    return {
      response: llmResponse.text, // Extract the text response
    };
  }
);
